export const appStrings = {
  loginScreen: {
    title: 'Login',
    emailLabel: 'Email',
    emailPlaceholder: 'Enter your email',
    passwordLabel: 'Password',
    passwordPlaceholder: 'Enter your password',
    loginButton: 'Login',
    goToSignup: 'Go to Signup',
    newUserText: 'New user?',
    wrongCredentials: 'Wrong credentials, New User? Signup',
  },
  signupScreen: {
    title: 'Sign Up',
    nameLabel: 'Name',
    namePlaceholder: 'Enter your name',
    emailLabel: 'Email',
    emailPlaceholder: 'Enter your email',
    passwordLabel: 'Password',
    passwordPlaceholder: 'Enter your password',
    signupButton: 'Sign Up',
    goToLogin: 'Go to Login',
  },
  homeScreen: {
    welcomeText: 'Welcome!',
    nameLabel: 'Name:',
    emailLabel: 'Email:',
    logoutButton: 'Logout',
  },
  errors: {
    emailRequired: 'Email is required',
    emailInvalid: 'Please enter a valid email',
    emailDomainLowercase: 'Email domain must be in lowercase (e.g., @gmail.com)',
    passwordRequired: 'Password is required',
    passwordMinLength: 'Password must be at least 8 characters',
    passwordCapitalRequired: 'Password must contain at least one capital letter',
    passwordLowercaseRequired: 'Password must contain at least one lowercase letter',
    passwordSymbolRequired: 'Password must contain at least one symbol',
    nameRequired: 'Name is required',
    invalidCredentials: 'Invalid email or password',
    signupFailed: 'Signup failed. Please try again.',
  },
  passwordHints: {
    minLength: 'Min 8 characters',
    capitalLetter: 'One capital letter',
    lowercaseLetter: 'One lowercase letter',
    symbol: 'One symbol',
  },
};

